# Generated by Django 2.1 on 2018-10-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20181009_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(null=True, verbose_name='Destaque'),
        ),
    ]
