# Generated by Django 2.1 on 2018-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0004_noticia_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=True, verbose_name='Destaque'),
        ),
    ]
