# Generated by Django 2.1 on 2018-10-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0005_auto_20181020_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
